"""init atlas schema"""

from alembic import op
import sqlalchemy as sa

revision = "0001_init"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("roles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(50), nullable=False, unique=True))
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("email", sa.String(255), nullable=False, unique=True), sa.Column("role", sa.String(50), nullable=False), sa.Column("hashed_password", sa.String(255), nullable=False), sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_table("user_roles", sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), primary_key=True), sa.Column("role_id", sa.Integer(), sa.ForeignKey("roles.id"), primary_key=True))
    op.create_table("projects", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_code", sa.String(120), unique=True), sa.Column("customer", sa.String(120)), sa.Column("oem", sa.String(120)), sa.Column("engine_type", sa.String(120)), sa.Column("engine_serial", sa.String(120)), sa.Column("status", sa.String(50)), sa.Column("baseline_start", sa.Date()), sa.Column("baseline_finish", sa.Date()), sa.Column("gate_state", sa.String(10)), sa.Column("created_at", sa.DateTime()))
    op.create_table("trolleys", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("trolley_code", sa.String(50), unique=True), sa.Column("location", sa.String(120)), sa.Column("status", sa.String(50)))
    op.create_table("project_trolleys", sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), primary_key=True), sa.Column("trolley_id", sa.Integer(), sa.ForeignKey("trolleys.id"), primary_key=True), sa.Column("active_from", sa.Date()), sa.Column("active_to", sa.Date()))
    op.create_table("activity_master", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("phase", sa.String(50)), sa.Column("main_activity", sa.String(255)), sa.Column("sub_activity", sa.String(255)), sa.Column("default_effort_hours", sa.Float()), sa.Column("gate_suggestion", sa.String(10)), sa.Column("requires_customer_parts", sa.Boolean()))
    op.create_table("project_activities", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("activity_master_id", sa.Integer(), sa.ForeignKey("activity_master.id")), sa.Column("status", sa.String(50)), sa.Column("planned_start", sa.Date()), sa.Column("planned_finish", sa.Date()), sa.Column("actual_start", sa.Date()), sa.Column("actual_finish", sa.Date()), sa.Column("percent_complete", sa.Float()), sa.Column("assigned_team", sa.String(120)), sa.Column("notes", sa.Text()), sa.Column("optimistic_hours", sa.Float()), sa.Column("most_likely_hours", sa.Float()), sa.Column("pessimistic_hours", sa.Float()))
    op.create_table("dependencies", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("predecessor_project_activity_id", sa.Integer(), sa.ForeignKey("project_activities.id")), sa.Column("successor_project_activity_id", sa.Integer(), sa.ForeignKey("project_activities.id")), sa.Column("relationship_type", sa.String(2)), sa.Column("lag_hours", sa.Float()))
    op.create_table("gates", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("gate_code", sa.String(2)), sa.Column("status", sa.String(30)), sa.Column("approved_by", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("approved_at", sa.DateTime()), sa.Column("comment", sa.Text()))
    op.create_table("daily_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("trolley_id", sa.Integer(), sa.ForeignKey("trolleys.id")), sa.Column("log_date", sa.Date()), sa.Column("shift", sa.String(20)), sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("summary", sa.Text()), sa.Column("blockers", sa.Text()), sa.Column("next_plan", sa.Text()), sa.Column("attachments_json", sa.JSON()))
    op.create_table("daily_log_activity_updates", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("daily_log_id", sa.Integer(), sa.ForeignKey("daily_logs.id")), sa.Column("project_activity_id", sa.Integer(), sa.ForeignKey("project_activities.id")), sa.Column("hours_spent", sa.Float()), sa.Column("progress_delta", sa.Float()), sa.Column("comment", sa.Text()))
    op.create_table("materials", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("part_number", sa.String(120), unique=True), sa.Column("description", sa.String(255)), sa.Column("category", sa.String(30)), sa.Column("criticality", sa.String(10)), sa.Column("default_lead_days", sa.Integer()))
    op.create_table("material_requirements", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("project_activity_id", sa.Integer(), sa.ForeignKey("project_activities.id")), sa.Column("material_id", sa.Integer(), sa.ForeignKey("materials.id")), sa.Column("quantity", sa.Float()), sa.Column("need_by_date", sa.Date()), sa.Column("ownership", sa.String(30)), sa.Column("status", sa.String(30)))
    op.create_table("material_orders", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("material_requirement_id", sa.Integer(), sa.ForeignKey("material_requirements.id")), sa.Column("ordered_on", sa.Date()), sa.Column("promised_on", sa.Date()), sa.Column("status", sa.String(30)), sa.Column("tracking_ref", sa.String(120)), sa.Column("supplier_name", sa.String(120)))
    op.create_table("issues", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("trolley_id", sa.Integer(), sa.ForeignKey("trolleys.id")), sa.Column("project_activity_id", sa.Integer(), sa.ForeignKey("project_activities.id")), sa.Column("issue_type", sa.String(30)), sa.Column("severity", sa.String(20)), sa.Column("status", sa.String(30)), sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("created_at", sa.DateTime()))
    op.create_table("root_causes", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("issue_id", sa.Integer(), sa.ForeignKey("issues.id")), sa.Column("method", sa.String(20)), sa.Column("category", sa.String(80)), sa.Column("five_whys_json", sa.JSON()), sa.Column("corrective_actions_json", sa.JSON()), sa.Column("verified_by", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("verified_at", sa.DateTime()))
    op.create_table("risks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("title", sa.String(255)), sa.Column("probability", sa.Float()), sa.Column("impact", sa.Float()), sa.Column("mitigation", sa.Text()), sa.Column("linked_activity_id", sa.Integer(), sa.ForeignKey("project_activities.id")), sa.Column("status", sa.String(30)))
    op.create_table("anomalies", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("anomaly_type", sa.String(40)), sa.Column("entity_type", sa.String(40)), sa.Column("entity_id", sa.Integer()), sa.Column("score", sa.Float()), sa.Column("detected_at", sa.DateTime()), sa.Column("explanation", sa.Text()))
    op.create_table("audit_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("actor_user_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("entity_type", sa.String(80)), sa.Column("entity_id", sa.Integer()), sa.Column("action", sa.String(20)), sa.Column("before_json", sa.JSON()), sa.Column("after_json", sa.JSON()), sa.Column("created_at", sa.DateTime()))


def downgrade() -> None:
    for t in ["audit_logs","anomalies","risks","root_causes","issues","material_orders","material_requirements","materials","daily_log_activity_updates","daily_logs","gates","dependencies","project_activities","activity_master","project_trolleys","trolleys","projects","user_roles","users","roles"]:
        op.drop_table(t)
