"""add atlas v2 twin tables"""

from alembic import op
import sqlalchemy as sa

revision = "0002_v2"
down_revision = "0001_init"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("v2_projects", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_code", sa.String(120), unique=True), sa.Column("name", sa.String(160)), sa.Column("customer", sa.String(120)), sa.Column("engine_type", sa.String(120)), sa.Column("engine_serial", sa.String(120)), sa.Column("start_target", sa.Date()), sa.Column("finish_target", sa.Date()), sa.Column("status", sa.String(40)), sa.Column("created_at", sa.DateTime()))
    op.create_table("v2_trolleys", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("trolley_code", sa.String(80), unique=True), sa.Column("location", sa.String(120)), sa.Column("status", sa.String(40)))
    op.create_table("v2_project_trolley", sa.Column("project_id", sa.Integer(), sa.ForeignKey("v2_projects.id"), primary_key=True), sa.Column("trolley_id", sa.Integer(), sa.ForeignKey("v2_trolleys.id"), primary_key=True), sa.Column("active_from", sa.Date()), sa.Column("active_to", sa.Date()))
    op.create_table("v2_templates", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(160), unique=True), sa.Column("description", sa.Text()), sa.Column("created_at", sa.DateTime()))
    op.create_table("v2_template_activities", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("template_id", sa.Integer(), sa.ForeignKey("v2_templates.id")), sa.Column("phase", sa.String(40)), sa.Column("activity_name", sa.String(180)), sa.Column("sub_activity", sa.String(180)), sa.Column("default_effort_hours", sa.Float()), sa.Column("default_materials_text", sa.Text()), sa.Column("default_tools_text", sa.Text()))
    op.create_table("v2_activities", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("v2_projects.id")), sa.Column("template_activity_id", sa.Integer(), sa.ForeignKey("v2_template_activities.id")), sa.Column("phase", sa.String(40)), sa.Column("activity_name", sa.String(180)), sa.Column("sub_activity", sa.String(180)), sa.Column("planned_start", sa.Date()), sa.Column("planned_finish", sa.Date()), sa.Column("forecast_start", sa.Date()), sa.Column("forecast_finish", sa.Date()), sa.Column("actual_start", sa.Date()), sa.Column("actual_finish", sa.Date()), sa.Column("status", sa.String(40)), sa.Column("percent_complete", sa.Float()), sa.Column("priority", sa.String(20)), sa.Column("owner", sa.String(120)), sa.Column("department", sa.String(120)), sa.Column("base_effort_hours", sa.Float()), sa.Column("notes", sa.Text()))
    op.create_table("v2_dependencies", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("v2_projects.id")), sa.Column("predecessor_activity_id", sa.Integer(), sa.ForeignKey("v2_activities.id")), sa.Column("successor_activity_id", sa.Integer(), sa.ForeignKey("v2_activities.id")), sa.Column("type", sa.String(2)), sa.Column("lag_hours", sa.Float()))
    op.create_table("v2_material_requirements", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("v2_projects.id")), sa.Column("activity_id", sa.Integer(), sa.ForeignKey("v2_activities.id")), sa.Column("part_number", sa.String(120)), sa.Column("description", sa.String(200)), sa.Column("ownership", sa.String(20)), sa.Column("criticality", sa.String(10)), sa.Column("need_by_date", sa.Date()), sa.Column("status", sa.String(30)), sa.Column("supplier_name", sa.String(120)), sa.Column("tracking_ref", sa.String(120)), sa.Column("promised_date", sa.Date()), sa.Column("received_date", sa.Date()), sa.Column("notes", sa.Text()))
    op.create_table("v2_daily_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("v2_projects.id")), sa.Column("trolley_id", sa.Integer(), sa.ForeignKey("v2_trolleys.id")), sa.Column("log_date", sa.Date()), sa.Column("created_by", sa.String(120)), sa.Column("summary", sa.Text()), sa.Column("blockers", sa.Text()), sa.Column("next_plan", sa.Text()), sa.Column("attachments_json", sa.JSON()))
    op.create_table("v2_daily_log_updates", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("daily_log_id", sa.Integer(), sa.ForeignKey("v2_daily_logs.id")), sa.Column("activity_id", sa.Integer(), sa.ForeignKey("v2_activities.id")), sa.Column("hours_spent", sa.Float()), sa.Column("progress_delta", sa.Float()), sa.Column("comment", sa.Text()))
    op.create_table("v2_delay_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("v2_projects.id")), sa.Column("activity_id", sa.Integer(), sa.ForeignKey("v2_activities.id")), sa.Column("detected_on", sa.Date()), sa.Column("delay_hours", sa.Float()), sa.Column("status", sa.String(20)), sa.Column("root_cause_category", sa.String(80)), sa.Column("root_cause_text", sa.Text()), sa.Column("five_whys_json", sa.JSON()))
    op.create_table("v2_action_items", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("v2_projects.id")), sa.Column("activity_id", sa.Integer(), sa.ForeignKey("v2_activities.id")), sa.Column("delay_event_id", sa.Integer(), sa.ForeignKey("v2_delay_events.id")), sa.Column("title", sa.String(200)), sa.Column("owner", sa.String(120)), sa.Column("due_date", sa.Date()), sa.Column("priority", sa.String(20)), sa.Column("status", sa.String(40)), sa.Column("notes", sa.Text()), sa.Column("updated_at", sa.DateTime()))
    op.create_table("v2_baselines", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("v2_projects.id")), sa.Column("name", sa.String(120)), sa.Column("created_at", sa.DateTime()), sa.Column("snapshot_json", sa.JSON()))


def downgrade() -> None:
    for t in ["v2_baselines","v2_action_items","v2_delay_events","v2_daily_log_updates","v2_daily_logs","v2_material_requirements","v2_dependencies","v2_activities","v2_template_activities","v2_templates","v2_project_trolley","v2_trolleys","v2_projects"]:
        op.drop_table(t)
